export const apiPaths = {
  health: '/api/health',
  ready: '/api/ready',
  diagnosis: '/api/diagnosis',
  recommendations: '/api/recommendations',
  recommendationExplanation: '/api/recommendations/:universityId/explanation',
  comparison: '/api/comparison',
  admissionsContact: '/api/universities/:universityId/admissions-contact',
  createLetter: '/api/universities/:universityId/letters',
  letterDrafts: '/api/letters/:letterId/drafts',
  letterContent: '/api/letters/:letterId/content',
  letterAttachments: '/api/letters/:letterId/attachments',
  letterAttachment: '/api/letters/:letterId/attachments/:attachmentId',
  roadmap: '/api/roadmap',
  profile: '/api/profile',
  plan: '/api/plan/:profileId',
  recalculate: '/api/plan/recalculate',
  roadmapItem: '/api/roadmaps/:roadmapId/items/:itemId',
} as const;
